[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
dynamic = ["version"]

name = "gemkid"
description = "MKID Layout generator for prototyping our UltimatE 1 MKID design"
readme = "README.md"

authors = [
  {name = "Aled Cuda"},
  {name = "Mazin Lab contributors"}
]
maintainers = [
  {name = "Aled V. Cuda", email = "aled@ucsb.edu"}
]

license = {file = "LICENSE.txt"}

requires-python = ">=3.11"
dependencies = [
  "numpy>=1.21",
  "gdstk>=0.9.50",
  "pandas>=2.2.2",
  "scipy>=1.11.1",
  "pyarrow>=16.1.0"
]

[project.optional-dependencies]
simulation = [
  "pysonnet@git+https://github.com/ld-cd/pysonnet.git",
  "loopfit@git+https://github.com/zobristnicholas/loopfit.git"
]

[tool.setuptools]
packages = ["gemkid"]

[tool.pdm.dev-dependencies]
dev = [
    "ipykernel>=6.29.5",
    "jupyterlab>=4.2.5",
]
